include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_key_in_widget_constructors

analyzer:
  errors:
    # Suppress errors from flutter_neumorphic package compatibility issues
    invalid_use_of_visible_for_testing_member: ignore
    invalid_override: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
